#add implementation
def add(x,y):
     return x+y    
#subtract implementation	 
def sub(x,y):
    return x-y	     
#multiply implementation
def mul(x,y):
     return x*y
#divide implementation
def div(x,y):
     return x/y   	 
#square implementation	 
def square(x):
     return x*x	 
